name: Scrape Homestuck

on:
  workflow_dispatch:

jobs:
  scrape:

    runs-on: ubuntu-latest

    timeout-minutes: 360

    permissions:
      contents: write

    steps:
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit changes
        run: |
          git add .
          git commit -m "whaa"
          git push
          
      # =====================================
      # Checkout repo
      # =====================================

      - name: Checkout repo
        uses: actions/checkout@v4

      # =====================================
      # Setup Node
      # =====================================

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # =====================================
      # Install Playwright
      # =====================================

      - name: Install Playwright
        run: |
          npm init -y
          npm install playwright
          npx playwright install chromium

      # =====================================
      # Run scraper
      # =====================================

      - name: Run scraper
        run: node scripts/scrape.js

      # =====================================
      # Commit JSON
      # =====================================

      - name: Commit JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add pages/

          git commit -m "Update scraped pages" || echo "No changes"

          git push
